version: '3.6'
services:
  service:
    build:
      context: .
      target: service
    ports:
      - "8080:8080"
    command: uvicorn openapi_server.main:app --host 0.0.0.0 --port 8080

  test_runner:
    build:
      context: .
      target: test_runner
    ports:
      - "8080:8080"
    environment:
      PYTHONPATH: src
    command: pytest -vv tests
